In [53]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [54]:
df = pd.read_parquet('../data/processed/data.parquet')

In [55]:
df = df.sort_values(by=['eom', 'id'], ascending = True)

In [56]:
df

,id,date,eom,source_crsp,size_grp,obs_main,exch_main,primary_sec,gvkey,iid,...,rvol_252d,zero_trades_252d,corr_1260d,betabab_1260d,rmax5_rvol_21d,age,qmj,qmj_prof,qmj_growth,qmj_safety
index,,,,,,,,,,,,,,,,,,,,,
58203,100100401,1981-01-31,1981-01-31,0,mega,1,1,1,1004.0,1.0,...,NaN,NaN,NaN,NaN,NaN,181,NaN,NaN,NaN,NaN
58731,100100501,1981-01-31,1981-01-31,0,mega,1,1,1,1005.0,1.0,...,NaN,NaN,NaN,NaN,NaN,97,NaN,NaN,NaN,NaN
58765,100101301,1981-01-31,1981-01-31,0,mega,1,1,1,1013.0,1.0,...,NaN,NaN,NaN,NaN,NaN,85,NaN,NaN,NaN,NaN
59125,100101601,1981-01-31,1981-01-31,0,mega,1,1,1,1016.0,1.0,...,NaN,NaN,NaN,NaN,NaN,85,NaN,NaN,NaN,NaN
59160,100101701,1981-01-31,1981-01-31,0,mega,1,1,1,1017.0,1.0,...,NaN,NaN,NaN,NaN,NaN,253,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2332866,135625701,2025-12-31,2025-12-31,0,mega,1,1,1,356257.0,1.0,...,NaN,NaN,NaN,NaN,NaN,152,NaN,NaN,NaN,NaN
2332889,135628901,2025-12-31,2025-12-31,0,mega,1,1,1,356289.0,1.0,...,NaN,NaN,NaN,NaN,NaN,60,NaN,NaN,NaN,NaN
2332902,135685901,2025-12-31,2025-12-31,0,mega,1,1,1,356859.0,1.0,...,NaN,NaN,NaN,NaN,NaN,36,NaN,NaN,NaN,NaN
2332909,136691101,2025-12-31,2025-12-31,0,mega,1,1,1,366911.0,1.0,...,NaN,NaN,NaN,NaN,NaN,48,NaN,NaN,NaN,NaN
2332910,136935001,2025-12-31,2025-12-31,0,mega,1,1,1,369350.0,1.0,...,NaN,NaN,NaN,NaN,NaN,36,NaN,NaN,NaN,NaN

In [57]:
for col in df.columns.to_list():
    print(col)

id
date
eom
source_crsp
size_grp
obs_main
exch_main
primary_sec
gvkey
iid
permno
permco
excntry
curcd
fx
common
comp_tpci
crsp_shrcd
comp_exchg
crsp_exchcd
adjfct
shares
me_lag1
gics
sic
naics
ff49
me_company
prc
prc_local
dolvol
ret_lag_dif
ret_exc_lead1m
enterprise_value
book_equity
assets
sales
net_income
bidask
prc_high
prc_low
tvol
div1m_me
div3m_me
div6m_me
div12m_me
divspc1m_me
divspc12m_me
chcsho_1m
chcsho_3m
chcsho_6m
chcsho_12m
eqnpo_1m
eqnpo_3m
eqnpo_6m
eqnpo_12m
ret_2_0
ret_3_0
ret_3_1
ret_6_0
ret_6_1
ret_9_0
ret_9_1
ret_12_0
ret_12_1
ret_12_7
ret_18_1
ret_24_1
ret_24_12
ret_36_1
ret_36_12
ret_48_12
ret_48_1
ret_60_1
ret_60_12
ret_60_36
seas_1_1an
seas_1_1na
seas_2_5an
seas_2_5na
seas_6_10an
seas_6_10na
seas_11_15an
seas_11_15na
seas_16_20an
seas_16_20na
at_gr1
ca_gr1
nca_gr1
lt_gr1
cl_gr1
ncl_gr1
be_gr1
pstk_gr1
debt_gr1
sale_gr1
cogs_gr1
sga_gr1
opex_gr1
capx_gr1
inv_gr1
at_gr3
ca_gr3
nca_gr3
lt_gr3
cl_gr3
ncl_gr3
be_gr3
pstk_gr3
debt_gr3
sale_gr3
cogs_gr3
sga_gr3
opex_gr3
capx_gr3
cash_gr1a
inv_gr1a
rec_gr1a
ppeg_gr1a
lti_gr1a
sti_gr1a
intan_gr1a
debtst_gr1a
ap_gr1a
txp_gr1a
debtlt_gr1a
txditc_gr1a
coa_gr1a
col_gr1a
cowc_gr1a
ncoa_gr1a
ncol_gr1a
nncoa_gr1a
oa_gr1a
ol_gr1a
fna_gr1a
fnl_gr1a
nfna_gr1a
gp_gr1a
ebitda_gr1a
ebit_gr1a
ope_gr1a
ni_gr1a
nix_gr1a
dp_gr1a
fincf_gr1a
ocf_gr1a
fcf_gr1a
nwc_gr1a
eqnetis_gr1a
dltnetis_gr1a
dstnetis_gr1a
dbnetis_gr1a
netis_gr1a
eqnpo_gr1a
tax_gr1a
eqbb_gr1a
eqis_gr1a
div_gr1a
eqpo_gr1a
capx_gr1a
be_gr1a
cash_gr3a
inv_gr3a
rec_gr3a
ppeg_gr3a
lti_gr3a
intan_gr3a
debtst_gr3a
ap_gr3a
txp_gr3a
debtlt_gr3a
txditc_gr3a
coa_gr3a
col_gr3a
cowc_gr3a
ncoa_gr3a
ncol_gr3a
nncoa_gr3a
oa_gr3a
ol_gr3a
fna_gr3a
fnl_gr3a
nfna_gr3a
gp_gr3a
ebitda_gr3a
ebit_gr3a
ope_gr3a
ni_gr3a
nix_gr3a
dp_gr3a
fincf_gr3a
ocf_gr3a
fcf_gr3a
nwc_gr3a
eqnetis_gr3a
dltnetis_gr3a
dstnetis_gr3a
dbnetis_gr3a
netis_gr3a
eqnpo_gr3a
tax_gr3a
eqbb_gr3a
eqis_gr3a
div_gr3a
eqpo_gr3a
capx_gr3a
capx_at
rd_at
spi_at
xido_at
nri_at
gp_sale
ebitda_sale
ebit_sale
pi_sale
ni_sale
nix_sale
ocf_sale
fcf_sale
gp_at
ebitda_at
ebit_at
fi_at
cop_at
ni_at
ope_be
ni_be
nix_be
ocf_be
fcf_be
gp_bev
ebitda_bev
ebit_bev
fi_bev
cop_bev
gp_ppen
ebitda_ppen
fcf_ppen
fincf_at
netis_at
eqnetis_at
eqis_at
dbnetis_at
dltnetis_at
dstnetis_at
eqnpo_at
eqbb_at
div_at
oaccruals_at
oaccruals_ni
taccruals_at
taccruals_ni
noa_at
be_bev
debt_bev
cash_bev
pstk_bev
debtlt_bev
debtst_bev
int_debt
int_debtlt
ebitda_debt
profit_cl
ocf_cl
ocf_debt
cash_lt
inv_act
rec_act
debtst_debt
cl_lt
debtlt_debt
lt_ppen
debtlt_be
opex_at
nwc_at
fcf_ocf
debt_at
debt_be
ebit_int
inv_days
rec_days
ap_days
cash_conversion
cash_cl
caliq_cl
ca_cl
inv_turnover
at_turnover
rec_turnover
ap_turnover
adv_sale
staff_sale
sale_bev
rd_sale
sale_be
div_ni
sale_nwc
tax_pi
cash_at
ni_emp
sale_emp
sale_emp_gr1
emp_gr1
ni_inc8q
noa_gr1a
ppeinv_gr1a
lnoa_gr1a
capx_gr2
saleq_gr1
niq_be
niq_at
niq_be_chg1
niq_at_chg1
rd5_at
dsale_dinv
dsale_drec
dgp_dsale
dsale_dsga
saleq_su
niq_su
capex_abn
op_atl1
gp_atl1
ope_bel1
cop_atl1
pi_nix
ocf_at
op_at
ocf_at_chg1
at_be
ocfq_saleq_std
niq_saleq_std
roeq_be_std
roe_be_std
tangibility
earnings_variability
aliq_at
f_score
o_score
z_score
intrinsic_value
kz_index
gpoa_ch5
roe_ch5
roa_ch5
cfoa_ch5
gmar_ch5
ni_ar1
ni_ivol
at_me
be_me
debt_me
netdebt_me
cash_me
sale_me
gp_me
ebitda_me
ebit_me
ope_me
ni_me
nix_me
cop_me
ocf_me
fcf_me
div_me
eqbb_me
eqis_me
eqpo_me
eqnpo_me
eqnetis_me
rd_me
ival_me
at_mev
bev_mev
ppen_mev
be_mev
cash_mev
sale_mev
gp_mev
ebitda_mev
ebit_mev
cop_mev
ocf_mev
fcf_mev
debt_mev
pstk_mev
debtlt_mev
debtst_mev
dltnetis_mev
dstnetis_mev
dbnetis_mev
netis_mev
fincf_mev
aliq_mat
eq_dur
beta_60m
ivol_capm_60m
mispricing_mgmt
mispricing_perf
beta_21d
beta_dimson_21d
bidaskhl_21d
coskew_21d
iskew_capm_21d
ivol_capm_21d
rmax1_21d
rmax5_21d
rskew_21d
rvol_21d
rvolhl_21d
zero_trades_21d
iskew_ff3_21d
iskew_hxz4_21d
ivol_ff3_21d
ivol_hxz4_21d
ami_126d
dolvol_126d
dolvol_var_126d
turnover_126d
turnover_var_126d
zero_trades_126d
beta_252d
betadown_252d
ivol_capm_252d
prc_highprc_252d
rvol_252d
zero_trades_252d
corr_1260d
betabab_1260d
rmax5_rvol_21d
age
qmj
qmj_prof
qmj_growth
qmj_safety

In [58]:
len(df.columns)

436

In [59]:
port = pd.read_csv('../data/backtest/lasso/portfolios.csv')
port

               id    leg    weight  predicted_ret  realized_ret         eom
0       101132801   long  0.003745       0.021027      0.361843  1981-02-28
1       101158401   long  0.003745       0.024544      0.091555  1981-02-28
2       100761601   long  0.003745       0.025219     -0.055710  1981-02-28
3       101081601   long  0.003745       0.032285      0.026843  1981-02-28
4       101085701   long  0.003745       0.023293      0.022709  1981-02-28
...           ...    ...       ...            ...           ...         ...
353863  102490102  short -0.003922      -0.064600     -0.077299  2025-10-31
353864  104179701  short -0.003922      -0.032025     -0.026446  2025-10-31
353865  101829001  short -0.003922      -0.032627     -0.038398  2025-10-31
353866  106363901  short -0.003922      -0.031862      0.185951  2025-10-31
353867  103778302  short -0.003922      -0.071097     -0.447561  2025-10-31

[353868 rows x 6 columns]

In [60]:
# port[(port['eom'] == '2018-06-30' and port['leg'] == 'short')]
temp = port[(port['eom'] == '2018-06-30') & (port['leg'] == 'short')]

In [61]:
temp

               id    leg    weight  predicted_ret  realized_ret         eom
306812  100851201  short -0.003356      -0.003029      0.040295  2018-06-30
306813  100816901  short -0.003356      -0.003051      0.037924  2018-06-30
306814  117981702  short -0.003356      -0.023358     -0.042459  2018-06-30
306815  118382601  short -0.003356      -0.002084     -0.059941  2018-06-30
306816  118565901  short -0.003356      -0.045397      0.025715  2018-06-30
...           ...    ...       ...            ...           ...         ...
307105  100834801  short -0.003356       0.001283     -0.044026  2018-06-30
307106  102490102  short -0.003356      -0.095205     -0.055627  2018-06-30
307107  101056502  short -0.003356      -0.034305      0.185099  2018-06-30
307108  112631801  short -0.003356      -0.011793     -0.092232  2018-06-30
307109  118549501  short -0.003356      -0.058960      0.032588  2018-06-30

[298 rows x 6 columns]

In [62]:
ticker_116646001 = df[df['id'] == 116646001]
ticker_116646001 = ticker_116646001[['eom', 'ret']]

KeyError: "['ret'] not in index"

In [ ]:
# Make sure eom is datetime
ticker_116646001['eom'] = pd.to_datetime(ticker_116646001['eom'])

# Sort by date
df = ticker_116646001.sort_values('eom').copy()

# Cumulative return
df['cum_ret'] = df['ret'].cumsum()

# Split into 3 equal chunks
n = len(df)
chunk_size = n // 3

chunks = [
    df.iloc[:chunk_size],
    df.iloc[chunk_size:2 * chunk_size],
    df.iloc[2 * chunk_size:]
]

for i, chunk in enumerate(chunks, 1):
    plt.figure(figsize=(12, 5))
    plt.plot(chunk['eom'], chunk['cum_ret'])
    plt.xlabel('EOM')
    plt.ylabel('Cumulative Return')
    plt.title(f'Cumulative Returns (Period {i})')
    plt.xticks(rotation=45)
    plt.grid(True)
    plt.tight_layout()
    plt.show()

In [ ]:
cum_ret = ticker_116646001['ret'].cumsum()

max_idx = cum_ret.idxmax()
max_return = cum_ret.loc[max_idx]
max_date = ticker_116646001.loc[max_idx, 'eom']

print(max_return)
print(max_date)

In [ ]:
cum_ret

In [ ]:
# there is a stock that I shorted on that day which generated a return of over 400 (not 400%). This is what caused the sharp spike in the cumulative return.

In [ ]:
ret_2018 = ticker_116646001.loc[
    ticker_116646001['eom'].dt.year == 2018,
    'ret'
]
ret_2018

In [ ]:
rets_df = pd.read_csv('../data/backtest/lasso/monthly_returns.csv')
# rets_df[['long_ret', 'short_ret']].cumsum().plot()
# rets = rets_df['long_ret'] - rets_df['short_ret']
# np.where(rets == rets.min())[0]

In [ ]:
rets_df

In [ ]:
xg_boost_ret = pd.read_csv('../data/backtest/xgboost_expanding/monthly_returns.csv')

In [ ]:
xg_boost_ret['net_qspread'].cumsum().plot()

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

series = xg_boost_ret['net_qspread'].cumsum()
n = len(series)
chunk = n // 3

fig, axes = plt.subplots(3, 1, figsize=(14, 10), tight_layout=True)

for i, ax in enumerate(axes):
    start = i * chunk
    end = n if i == 2 else (i + 1) * chunk
    ax.plot(series.index[start:end], series.iloc[start:end])
    ax.set_title(f'Part {i+1}: {series.index[start]} → {series.index[end-1]}')
    ax.grid(True, alpha=0.3)

plt.show()